version: '3'
services:
  app:
    build: ./php7.4-xdebug
    ports:
    - "80:80"
    volumes:
    - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=172.20.0.1

  mysql:
    image: mysql:5.7
    ports:
    - "3306:3306"
    volumes:
    - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: tasker
      MYSQL_ROOT_PASSWORD: roottasker